services:
  tracking:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318" # OpenTelemetry receiver
      - "14268:14268" # Jaeger receiver
      - "16686:16686" # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  prism:
    image: stoplight/prism:latest
    ports:
      - "4010:4010"
    command:
      - mock
      - -h
      - 0.0.0.0
      - /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml

volumes:
  db-data:
  event-data:
  event-logs: